plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'pumpkin.anuncios'
version = '2.3'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
    compileOnly 'io.papermc.paper:paper-api:1.19.4-R0.1-SNAPSHOT'
    implementation 'org.spongepowered:configurate-yaml:4.1.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks {
    shadowJar {
        archiveClassifier.set('')

        // PRÁCTICA PRO: Reubicar librerías.
        // Si otro plugin usa un Configurate antiguo, el tuyo no se romperá ni causará errores.
        relocate 'org.spongepowered.configurate', 'pumpkin.anuncios.libs.configurate'
        relocate 'io.leangen.geantyref', 'pumpkin.anuncios.libs.geantyref'
    }
}

build.dependsOn shadowJar
