settings:
  cooldown-seconds: 60

messages:
  help: "<gradient:gold:yellow><bold>PumpkinAnnouncer</bold></gradient>\n<gray>» <yellow>/pa reload <dark_gray>- <white>Reload settings\n<gray>» <yellow>/pa list <dark_gray>- <white>View all IDs\n<gray>» <yellow>/pa test <id> <dark_gray>- <white>Preview an announcement"
  reload-success: "<green>Reload complete! Everything is running smoothly."
  list-header: "<gold><bold>Currently Loaded Announcements:</bold></gold>"
  id-not-found: "<red>That announcement ID doesn't exist. Please check your config."

# Sound List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

announcements:
  discord:
    # Use ["global"] to display on all servers, or specify like ["lobby", "survival"]
    servers: ["global"]
    # [PAPER ONLY] Specify which worlds will see this. Ignored on Velocity.
    # Use["global"] to display in all worlds. Example for specific worlds: ["world", "world_nether"]
    worlds: ["global"]

    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    actionbar:
      enabled: true
      text: "<color:#A0C4FF><bold>Join our official Discord community!</bold></color>"
      duration-seconds: 10
    bossbar:
      enabled: true
      text: "<color:#A0C4FF><bold>OFFICIAL DISCORD</bold></color>"
      color: "BLUE" # Options: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
      style: "SOLID" # Options: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
      duration-seconds: 10
      deplete: true
    lines:
      - "[center]<color:#A0C4FF><bold>DISCORD</bold>"
      - ""
      - "[center]<white>Come and be part of our community!"
      - "[center]<white>Link: <click:open_url:'your_link'><hover:show_text:'<gray>Click here to join!'><underlined><color:#A0C4FF>your_link</color></underlined></hover></click>"
      - "[center]<gray>» <white>Giveaways, support, and daily updates."

  security:
    servers: ["global"]
    worlds: ["global"]
    sound: ""
    actionbar:
      enabled: false
    bossbar:
      enabled: false
    lines:
      - "[center]<color:#FFADAD><bold>SECURITY TIP</bold>"
      - ""
      - "[center]<white>To keep your account safe, we recommend <color:#FFD6A5><bold>avoiding</bold></color>"
      - "[center]<white>the use of the same password across different servers."
      - "[center]<gray>» <white>Protect your progress by using unique passwords."
      
