import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Importamos el Provider que creamos
import { PlaceholderProvider } from "@/app/context/PlaceholderContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Envolvemos todo con el Provider. 
            Ahora cualquier componente adentro (como el Switch o el Tooltip)
            va a compartir el mismo estado, ¡simón que sí!
        */}
        <PlaceholderProvider>
          {children}
        </PlaceholderProvider>
      </body>
    </html>
  );
}
